language: node_js
node_js:
  - "8" 
script:
  - ng build
  - firebase deploy --project anti-auctions --token $FIREBASE_TOKEN
install:
  - npm install
  - npm install -g --silent firebase-tools
  - npm install -g --silent @angular/cli
  
branches:
  only:
  - master
  - dev
